// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/greeting_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GreetingRequest_Gender int32

const (
	GreetingRequest_MALE   GreetingRequest_Gender = 0
	GreetingRequest_FEMALE GreetingRequest_Gender = 1
	GreetingRequest_OTHER  GreetingRequest_Gender = 2
)

// Enum value maps for GreetingRequest_Gender.
var (
	GreetingRequest_Gender_name = map[int32]string{
		0: "MALE",
		1: "FEMALE",
		2: "OTHER",
	}
	GreetingRequest_Gender_value = map[string]int32{
		"MALE":   0,
		"FEMALE": 1,
		"OTHER":  2,
	}
)

func (x GreetingRequest_Gender) Enum() *GreetingRequest_Gender {
	p := new(GreetingRequest_Gender)
	*p = x
	return p
}

func (x GreetingRequest_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GreetingRequest_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_greeting_service_proto_enumTypes[0].Descriptor()
}

func (GreetingRequest_Gender) Type() protoreflect.EnumType {
	return &file_proto_greeting_service_proto_enumTypes[0]
}

func (x GreetingRequest_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GreetingRequest_Gender.Descriptor instead.
func (GreetingRequest_Gender) EnumDescriptor() ([]byte, []int) {
	return file_proto_greeting_service_proto_rawDescGZIP(), []int{0, 0}
}

type GreetingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age    int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Gender GreetingRequest_Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=GreetingRequest_Gender" json:"gender,omitempty"`
}

func (x *GreetingRequest) Reset() {
	*x = GreetingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_greeting_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingRequest) ProtoMessage() {}

func (x *GreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeting_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingRequest.ProtoReflect.Descriptor instead.
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeting_service_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GreetingRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GreetingRequest) GetGender() GreetingRequest_Gender {
	if x != nil {
		return x.Gender
	}
	return GreetingRequest_MALE
}

var File_proto_greeting_service_proto protoreflect.FileDescriptor

var file_proto_greeting_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x93, 0x01, 0x0a,
	0x0f, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x46,
	0x45, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x4f, 0x54, 0x48, 0x45, 0x52,
	0x10, 0x02, 0x32, 0x39, 0x0a, 0x0f, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x10,
	0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x09, 0x2e, 0x47, 0x72, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x22, 0x00, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_greeting_service_proto_rawDescOnce sync.Once
	file_proto_greeting_service_proto_rawDescData = file_proto_greeting_service_proto_rawDesc
)

func file_proto_greeting_service_proto_rawDescGZIP() []byte {
	file_proto_greeting_service_proto_rawDescOnce.Do(func() {
		file_proto_greeting_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_greeting_service_proto_rawDescData)
	})
	return file_proto_greeting_service_proto_rawDescData
}

var file_proto_greeting_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_greeting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_greeting_service_proto_goTypes = []interface{}{
	(GreetingRequest_Gender)(0), // 0: GreetingRequest.Gender
	(*GreetingRequest)(nil),     // 1: GreetingRequest
	(*Greeting)(nil),            // 2: Greeting
}
var file_proto_greeting_service_proto_depIdxs = []int32{
	0, // 0: GreetingRequest.gender:type_name -> GreetingRequest.Gender
	1, // 1: GreetingService.Hello:input_type -> GreetingRequest
	2, // 2: GreetingService.Hello:output_type -> Greeting
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_greeting_service_proto_init() }
func file_proto_greeting_service_proto_init() {
	if File_proto_greeting_service_proto != nil {
		return
	}
	file_proto_greeting_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_greeting_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GreetingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_greeting_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeting_service_proto_goTypes,
		DependencyIndexes: file_proto_greeting_service_proto_depIdxs,
		EnumInfos:         file_proto_greeting_service_proto_enumTypes,
		MessageInfos:      file_proto_greeting_service_proto_msgTypes,
	}.Build()
	File_proto_greeting_service_proto = out.File
	file_proto_greeting_service_proto_rawDesc = nil
	file_proto_greeting_service_proto_goTypes = nil
	file_proto_greeting_service_proto_depIdxs = nil
}
